In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler,StandardScaler
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV

In [2]:
df=pd.read_csv("heart.csv")
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        303 non-null    int64  
 12  thal      303 non-null    int64  
 13  target    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [4]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [5]:
df.describe()

age         sex          cp    trestbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.366337    0.683168    0.966997  131.623762  246.264026    0.148515   
std      9.082101    0.466011    1.032052   17.538143   51.830751    0.356198   
min     29.000000    0.000000    0.000000   94.000000  126.000000    0.000000   
25%     47.500000    0.000000    0.000000  120.000000  211.000000    0.000000   
50%     55.000000    1.000000    1.000000  130.000000  240.000000    0.000000   
75%     61.000000    1.000000    2.000000  140.000000  274.500000    0.000000   
max     77.000000    1.000000    3.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope          ca  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.528053  149.646865    0.326733    1.039604    1.399340    0.729373   
std      0.525860   22.905161    0.469794    1.161075    0.616226    1.022606   
min      0.000000   71.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000  133.500000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  153.000000    0.000000    0.800000    1.000000    0.000000   
75%      1.000000  166.000000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    2.000000    4.000000   

             thal      target  
count  303.000000  303.000000  
mean     2.313531    0.544554  
std      0.612277    0.498835  
min      0.000000    0.000000  
25%      2.000000    0.000000  
50%      2.000000    1.000000  
75%      3.000000    1.000000  
max      3.000000    1.000000

In [6]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [7]:
x=df.drop(["target"],axis=1)
y=df["target"]

In [8]:
x

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  
0        0   0     1  
1        0   0     2  
2        2   0     2  
3        2   0     2  
4        2   0     2  
..     ...  ..   ...  
298      1   0     3  
299      1   0     3  
300      1   2     3  
301      1   1     3  
302      1   1     2  

[303 rows x 13 columns]

In [9]:
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

### MinMaxScaler

In [10]:
normal_scaler=MinMaxScaler(feature_range=(0,1))
x_scaled=normal_scaler.fit_transform(x)
x_scaled
x_normal_df=pd.DataFrame(x_scaled,columns=x.columns)
x_normal_df

age  sex        cp  trestbps      chol  fbs  restecg   thalach  \
0    0.708333  1.0  1.000000  0.481132  0.244292  1.0      0.0  0.603053   
1    0.166667  1.0  0.666667  0.339623  0.283105  0.0      0.5  0.885496   
2    0.250000  0.0  0.333333  0.339623  0.178082  0.0      0.0  0.770992   
3    0.562500  1.0  0.333333  0.245283  0.251142  0.0      0.5  0.816794   
4    0.583333  0.0  0.000000  0.245283  0.520548  0.0      0.5  0.702290   
..        ...  ...       ...       ...       ...  ...      ...       ...   
298  0.583333  0.0  0.000000  0.433962  0.262557  0.0      0.5  0.396947   
299  0.333333  1.0  1.000000  0.150943  0.315068  0.0      0.5  0.465649   
300  0.812500  1.0  0.000000  0.471698  0.152968  1.0      0.5  0.534351   
301  0.583333  1.0  0.000000  0.339623  0.011416  0.0      0.5  0.335878   
302  0.583333  0.0  0.333333  0.339623  0.251142  0.0      0.0  0.786260   

     exang   oldpeak  slope    ca      thal  
0      0.0  0.370968    0.0  0.00  0.333333  
1      0.0  0.564516    0.0  0.00  0.666667  
2      0.0  0.225806    1.0  0.00  0.666667  
3      0.0  0.129032    1.0  0.00  0.666667  
4      1.0  0.096774    1.0  0.00  0.666667  
..     ...       ...    ...   ...       ...  
298    1.0  0.032258    0.5  0.00  1.000000  
299    0.0  0.193548    0.5  0.00  1.000000  
300    0.0  0.548387    0.5  0.50  1.000000  
301    1.0  0.193548    0.5  0.25  1.000000  
302    0.0  0.000000    0.5  0.25  0.666667  

[303 rows x 13 columns]

### Standardscaler

In [11]:
std_scaler=StandardScaler()
x_scaled=std_scaler.fit_transform(x)
x_scaled
x_std_df=pd.DataFrame(x_scaled,columns=x.columns)
x_std_df

age       sex        cp  trestbps      chol       fbs   restecg  \
0    0.952197  0.681005  1.973123  0.763956 -0.256334  2.394438 -1.005832   
1   -1.915313  0.681005  1.002577 -0.092738  0.072199 -0.417635  0.898962   
2   -1.474158 -1.468418  0.032031 -0.092738 -0.816773 -0.417635 -1.005832   
3    0.180175  0.681005  0.032031 -0.663867 -0.198357 -0.417635  0.898962   
4    0.290464 -1.468418 -0.938515 -0.663867  2.082050 -0.417635  0.898962   
..        ...       ...       ...       ...       ...       ...       ...   
298  0.290464 -1.468418 -0.938515  0.478391 -0.101730 -0.417635  0.898962   
299 -1.033002  0.681005  1.973123 -1.234996  0.342756 -0.417635  0.898962   
300  1.503641  0.681005 -0.938515  0.706843 -1.029353  2.394438  0.898962   
301  0.290464  0.681005 -0.938515 -0.092738 -2.227533 -0.417635  0.898962   
302  0.290464 -1.468418  0.032031 -0.092738 -0.198357 -0.417635 -1.005832   

      thalach     exang   oldpeak     slope        ca      thal  
0    0.015443 -0.696631  1.087338 -2.274579 -0.714429 -2.148873  
1    1.633471 -0.696631  2.122573 -2.274579 -0.714429 -0.512922  
2    0.977514 -0.696631  0.310912  0.976352 -0.714429 -0.512922  
3    1.239897 -0.696631 -0.206705  0.976352 -0.714429 -0.512922  
4    0.583939  1.435481 -0.379244  0.976352 -0.714429 -0.512922  
..        ...       ...       ...       ...       ...       ...  
298 -1.165281  1.435481 -0.724323 -0.649113 -0.714429  1.123029  
299 -0.771706 -0.696631  0.138373 -0.649113 -0.714429  1.123029  
300 -0.378132 -0.696631  2.036303 -0.649113  1.244593  1.123029  
301 -1.515125  1.435481  0.138373 -0.649113  0.265082  1.123029  
302  1.064975 -0.696631 -0.896862 -0.649113  0.265082 -0.512922  

[303 rows x 13 columns]

In [42]:
x_train,x_test,y_train,y_test=train_test_split(x_normal_df,y,test_size=0.2,random_state=1,stratify=y)
x_train

age  sex        cp  trestbps      chol  fbs  restecg   thalach  \
293  0.791667  1.0  0.666667  0.547170  0.196347  0.0      0.0  0.603053   
99   0.500000  1.0  0.666667  0.339623  0.273973  1.0      0.0  0.778626   
271  0.666667  1.0  1.000000  0.377358  0.246575  0.0      0.5  0.564885   
81   0.333333  1.0  0.333333  0.320755  0.415525  0.0      0.0  0.755725   
257  0.437500  1.0  0.000000  0.471698  0.168950  0.0      0.0  0.419847   
..        ...  ...       ...       ...       ...  ...      ...       ...   
196  0.354167  1.0  0.666667  0.528302  0.239726  0.0      0.5  0.580153   
191  0.604167  1.0  0.000000  0.320755  0.205479  0.0      0.0  0.458015   
275  0.479167  1.0  0.000000  0.292453  0.196347  0.0      0.5  0.740458   
192  0.520833  1.0  0.000000  0.245283  0.141553  0.0      0.5  0.320611   
161  0.541667  0.0  0.333333  0.358491  0.493151  0.0      0.5  0.725191   

     exang   oldpeak  slope    ca      thal  
293    0.0  0.129032    0.5  0.00  1.000000  
99     0.0  0.000000    1.0  0.75  0.666667  
271    0.0  0.419355    0.5  0.50  0.666667  
81     0.0  0.000000    1.0  0.00  0.666667  
257    1.0  0.145161    0.5  0.00  1.000000  
..     ...       ...    ...   ...       ...  
196    0.0  0.580645    0.5  0.00  0.666667  
191    1.0  0.354839    0.5  0.75  1.000000  
275    0.0  0.161290    1.0  0.50  1.000000  
192    0.0  0.225806    0.5  0.25  1.000000  
161    0.0  0.193548    1.0  0.00  0.666667  

[242 rows x 13 columns]

In [43]:
y_train.value_counts()

1    132
0    110
Name: target, dtype: int64

In [44]:
y_test.value_counts()

1    33
0    28
Name: target, dtype: int64

In [45]:
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [46]:
param_grid={"n_neighbors":np.arange(2,10),
           "p":[1,2]}
param_grid

{'n_neighbors': array([2, 3, 4, 5, 6, 7, 8, 9]), 'p': [1, 2]}

In [55]:
knn_clf=KNeighborsClassifier()
knn_clf

KNeighborsClassifier()

In [57]:
gscv=GridSearchCV(knn_clf,param_grid,cv=10)
gscv.fit(x_train,y_train)

GridSearchCV(cv=10, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': array([2, 3, 4, 5, 6, 7, 8, 9]),
                         'p': [1, 2]})

In [59]:
gscv.best_estimator_

KNeighborsClassifier(n_neighbors=7, p=1)

In [60]:
gscv.best_params_

{'n_neighbors': 7, 'p': 1}

In [69]:
rscv=RandomizedSearchCV(knn_clf,param_grid,cv=5)
rscv.fit(x_train,y_train)

RandomizedSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=7, p=1),
                   param_distributions={'n_neighbors': array([2, 3, 4, 5, 6, 7, 8, 9]),
                                        'p': [1, 2]})

In [70]:
rscv.best_estimator_

KNeighborsClassifier(n_neighbors=6, p=1)

In [71]:
rscv.best_params_

{'p': 1, 'n_neighbors': 6}

In [72]:
knn_clf=KNeighborsClassifier(n_neighbors=6,p=1)
knn_clf.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=6, p=1)

In [73]:
y_pred=knn_clf.predict(x_test)
y_pred

array([0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0], dtype=int64)

In [74]:
y_test

172    0
261    0
142    1
114    1
43     1
      ..
289    0
291    0
236    0
141    1
150    1
Name: target, Length: 61, dtype: int64

In [75]:
y_pred[:5]

array([0, 0, 1, 1, 1], dtype=int64)

In [76]:
y_test[:5]

172    0
261    0
142    1
114    1
43     1
Name: target, dtype: int64

In [77]:
confusion_matrix(y_test,y_pred)

array([[23,  5],
       [ 7, 26]], dtype=int64)

In [78]:
clf=classification_report(y_test,y_pred)
print(clf)

              precision    recall  f1-score   support

           0       0.77      0.82      0.79        28
           1       0.84      0.79      0.81        33

    accuracy                           0.80        61
   macro avg       0.80      0.80      0.80        61
weighted avg       0.81      0.80      0.80        61



In [79]:
accuracy_score(y_test,y_pred)

0.8032786885245902

### Final Report